package fun.commons.framework4j.datasource.tracing;

import com.alibaba.druid.filter.FilterChain;
import com.alibaba.druid.filter.FilterEventAdapter;
import com.alibaba.druid.proxy.jdbc.ConnectionProxy;
import com.alibaba.druid.proxy.jdbc.PreparedStatementProxy;
import com.alibaba.druid.proxy.jdbc.ResultSetProxy;
import com.alibaba.druid.proxy.jdbc.StatementProxy;
import lombok.extern.slf4j.Slf4j;

import java.sql.SQLException;
import java.util.Locale;

/**
 * Druid SQL 追踪过滤器
 * <p>
 * 在 SQL 前添加注释，包括 traceid 和 topic（应用名）。
 * 格式：/*traceid=abc,topic=app-name* / SELECT ...
 * <p>
 * 支持三种追踪模式:
 * - DISABLED: 不开启追踪
 * - WRITE_ONLY: 仅追踪写操作 (INSERT, UPDATE, DELETE)
 * - ALL: 追踪所有 SQL (SELECT, INSERT, UPDATE, DELETE 等)
 *
 * @since 1.0.0
 */
@Slf4j
public class TraceIdDruidFilter extends FilterEventAdapter {

    private final TraceIdProvider traceIdProvider;
    private final String topic;
    private final SqlTracingProperties.TracingMode tracingMode;

    public TraceIdDruidFilter(TraceIdProvider traceIdProvider, String topic, SqlTracingProperties.TracingMode tracingMode) {
        this.traceIdProvider = traceIdProvider;
        this.topic = topic != null ? topic : "unknown";
        this.tracingMode = tracingMode != null ? tracingMode : SqlTracingProperties.TracingMode.DISABLED;
    }

    // ==================== PreparedStatement 拦截 ====================

    @Override
    public PreparedStatementProxy connection_prepareStatement(FilterChain chain, ConnectionProxy connection, String sql) throws SQLException {
        String finalSql = processSql(sql);
        return super.connection_prepareStatement(chain, connection, finalSql);
    }

    @Override
    public PreparedStatementProxy connection_prepareStatement(FilterChain chain, ConnectionProxy connection, String sql, int autoGeneratedKeys) throws SQLException {
        String finalSql = processSql(sql);
        return super.connection_prepareStatement(chain, connection, finalSql, autoGeneratedKeys);
    }

    @Override
    public PreparedStatementProxy connection_prepareStatement(FilterChain chain, ConnectionProxy connection, String sql, int[] columnIndexes) throws SQLException {
        String finalSql = processSql(sql);
        return super.connection_prepareStatement(chain, connection, finalSql, columnIndexes);
    }

    @Override
    public PreparedStatementProxy connection_prepareStatement(FilterChain chain, ConnectionProxy connection, String sql, String[] columnNames) throws SQLException {
        String finalSql = processSql(sql);
        return super.connection_prepareStatement(chain, connection, finalSql, columnNames);
    }

    @Override
    public PreparedStatementProxy connection_prepareStatement(FilterChain chain, ConnectionProxy connection, String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        String finalSql = processSql(sql);
        return super.connection_prepareStatement(chain, connection, finalSql, resultSetType, resultSetConcurrency);
    }

    @Override
    public PreparedStatementProxy connection_prepareStatement(FilterChain chain, ConnectionProxy connection, String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        String finalSql = processSql(sql);
        return super.connection_prepareStatement(chain, connection, finalSql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    // ==================== Statement execute 拦截 ====================

    @Override
    public boolean statement_execute(FilterChain chain, StatementProxy statement, String sql) throws SQLException {
        String finalSql = processSql(sql);
        return super.statement_execute(chain, statement, finalSql);
    }

    @Override
    public boolean statement_execute(FilterChain chain, StatementProxy statement, String sql, int autoGeneratedKeys) throws SQLException {
        String finalSql = processSql(sql);
        return super.statement_execute(chain, statement, finalSql, autoGeneratedKeys);
    }

    @Override
    public boolean statement_execute(FilterChain chain, StatementProxy statement, String sql, int[] columnIndexes) throws SQLException {
        String finalSql = processSql(sql);
        return super.statement_execute(chain, statement, finalSql, columnIndexes);
    }

    @Override
    public boolean statement_execute(FilterChain chain, StatementProxy statement, String sql, String[] columnNames) throws SQLException {
        String finalSql = processSql(sql);
        return super.statement_execute(chain, statement, finalSql, columnNames);
    }

    // ==================== Statement executeUpdate 拦截 ====================

    @Override
    public int statement_executeUpdate(FilterChain chain, StatementProxy statement, String sql) throws SQLException {
        String finalSql = processSql(sql);
        return super.statement_executeUpdate(chain, statement, finalSql);
    }

    @Override
    public int statement_executeUpdate(FilterChain chain, StatementProxy statement, String sql, int autoGeneratedKeys) throws SQLException {
        String finalSql = processSql(sql);
        return super.statement_executeUpdate(chain, statement, finalSql, autoGeneratedKeys);
    }

    @Override
    public int statement_executeUpdate(FilterChain chain, StatementProxy statement, String sql, int[] columnIndexes) throws SQLException {
        String finalSql = processSql(sql);
        return super.statement_executeUpdate(chain, statement, finalSql, columnIndexes);
    }

    @Override
    public int statement_executeUpdate(FilterChain chain, StatementProxy statement, String sql, String[] columnNames) throws SQLException {
        String finalSql = processSql(sql);
        return super.statement_executeUpdate(chain, statement, finalSql, columnNames);
    }

    // ==================== Statement executeQuery 拦截 ====================

    @Override
    public ResultSetProxy statement_executeQuery(FilterChain chain, StatementProxy statement, String sql) throws SQLException {
        String finalSql = processSql(sql);
        return super.statement_executeQuery(chain, statement, finalSql);
    }

    // ==================== SQL 处理核心逻辑 ====================

    /**
     * SQL 处理核心逻辑
     * <p>
     * 格式: /*traceid=xxx,topic=xxx* / SQL
     */
    private String processSql(String sql) {
        if (tracingMode == SqlTracingProperties.TracingMode.DISABLED) {
            return sql;
        }
        if (sql == null || sql.isBlank()) {
            return sql;
        }
        try {
            String trimmedSql = sql.trim();
            if (trimmedSql.startsWith("/*traceid=")) {
                return sql;
            }
            if (tracingMode == SqlTracingProperties.TracingMode.WRITE_ONLY && isReadOperation(trimmedSql)) {
                return sql;
            }
            String traceId = getTraceId();
            if (log.isDebugEnabled()) {
                log.debug("[SQL Tracing] TraceId={}, Topic={}, SQL={}", traceId, topic, trimmedSql.substring(0, Math.min(50, trimmedSql.length())));
            }
            StringBuilder sb = new StringBuilder(sql.length() + 64 + traceId.length() + topic.length());
            sb.append("/*traceid=").append(sanitize(traceId))
                    .append(",topic=").append(sanitize(topic))
                    .append("*/ ")
                    .append(sql);
            return sb.toString();
        } catch (Exception e) {
            log.warn("Failed to inject TraceID into SQL: {}", e.getMessage());
            return sql;
        }
    }

    private boolean isReadOperation(String sql) {
        String upperSql = sql.toUpperCase(Locale.ROOT);
        return upperSql.startsWith("SELECT ")
                || upperSql.startsWith("SELECT\t")
                || upperSql.startsWith("SELECT\n")
                || upperSql.startsWith("SELECT\r")
                || upperSql.startsWith("(SELECT ")
                || upperSql.startsWith("( SELECT ")
                || upperSql.startsWith("SHOW ")
                || upperSql.startsWith("DESCRIBE ")
                || upperSql.startsWith("DESC ")
                || upperSql.startsWith("EXPLAIN ");
    }

    private String getTraceId() {
        if (traceIdProvider == null) {
            return "none";
        }
        String traceId = traceIdProvider.getTraceId();
        if (traceId == null || traceId.isBlank()) {
            return "none";
        }
        return traceId;
    }

    /**
     * 过滤特殊字符，防止注入攻击和注释结构破坏。
     * v2.1 安全加固：改白名单策略，仅允许字母数字 + - _ . ，其余替换为下划线。
     * 原黑名单可能被星号、斜杠、空字节等绕过破坏注释结构。
     */
    private String sanitize(String value) {
        if (value == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder(value.length());
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                    || (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.') {
                sb.append(c);
            } else {
                sb.append('_');
            }
        }
        return sb.toString();
    }
}
